const rawData = `
8 | ACID | Acid làm đổi màu quỳ tím | Ống nhỏ giọt, Chén thủy tinh | Hydrochloric acid, Quỳ tím |  | Dung dịch acid làm giấy quỳ tím chuyển sang màu đỏ. | Giấy quỳ tím chuyển sang màu đỏ |
8 | ACID | Acid tác dụng với kim loại | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt, Muỗng lấy hóa chất | Hydrochloric acid, Zinc (kẽm) | Zn+2HCl→ZnCl2+H2 | Một số kim loại  tác dụng với dung dịch acid tạo thành muối và khí hydrogen. | Dung dịch không màu, sủi bọt khí |
8 | BASE | Dung dịch base làm đổi màu chất chỉ thị | Ống nhỏ giọt, Chén thủy tinh | Sodium hydroxide, Quỳ tím, Phenolphtalein |  | Dung dịch base làm quỳ tím chuyển sang màu xanh, dung dịch phenolphtalein không màu chuyển sang màu hồng. | Giấy quỳ tím chuyển sang màu xanh dương, dung dịch phenolphtalein không màu chuyển sang màu hồng. | Quỳ tím,Phenolphtalein
8 | BASE | Base tác dụng với dung dịch acid | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt | Barium hydroxide, Sulfuric acid | Ba(OH)2+ H2SO4→BaSO4+2H2O | Base tác dụng với dung dịch acid tạo thành muối và nước. | Xuất hiện chất kết tủa màu trắng. |
8 | MUỐI | Dung dịch muối tác dụng với kim loại | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt, Kẹp gắp | Đinh sắt (Iron), Copper(II)sulfate | Fe + CuSO4 → FeSO4 + Cu | Dung dịch muối có thể tác dụng với một số kim loại tạo thành muối mới và kim loại mới. | Đinh sắt bị bao phủ bởi lớp kim loại màu đỏ gạch, màu xanh dung dịch ban đầu nhạt dần. |
8 | MUỐI | Muối tác dụng dung dịch acid | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt | Sulfuric acid, Barium chloride | BaCl2+H2SO4→BaSO4+2HCl | Muối có thể tác dụng với một số dung dịch acid tạo thành muối mới và acid mới. | Xuất hiện chất kết tủa màu trắng. |
8 | MUỐI | Dung dịch muối tác dụng với dung dịch base | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt | Sodium hydroxide, Copper(II)sulfate | 2NaOH+CuSO4→Na2SO4+Cu(OH)2 | Dung dịch muối tác dụng với dung dịch base tạo thành muối mới và base mới. | xuất hiện chất kết tủa màu xanh lơ, màu xanh của dung dịch bị nhạt dần. |
8 | MUỐI | Dung dịch muối tác dụng với dung dịch muối | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt | Barium chloride, Sodium sulfate | BaCl2+Na2SO4→BaSO4+2NaCl | Hai dung dịch muối tác dụng với nhau tạo thành hai muối mới. | Xuất hiện chất kết tủa màu trắng. |
9 | CARBOHYDRATE. GLUCOSE VÀ SACCHOROSE | Phản ứng tráng gương | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt, Đèn cồn, Kẹp gỗ ống nghiệm | Glucose 1%, Silver nitrate 1%, Ammonia 5% | C6H12O6 + Ag2O → C6H12O7 + 2Ag | Dung dịch A gờ N O 3 trong N H 3 đã oxi hoá glucose tạo thành muối amoni gluconat và bạc kim loại bám vào thành ống nghiệm. | Thành ống nghiệm sáng bóng như gương. | Ammonia 5%
9 | ACETIC ACID | Acetic acid tác dụng với muối carbonate | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt, Muỗng lấy hóa chất | Acetic acid 10%, Calcium carbonate | 2CH₃COOH + CaCO₃ → (CH₃COO)₂Ca + CO₂↑ + H₂O | Acetic acid phản ứng với muối carbonate tạo muối, CO₂ và nước. | Sủi bọt khí xê ô 2 |
9 | TÍNH CHẤT CHUNG CỦA KIM LOẠI | Kim loại phản ứng với muối | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt, Kẹp ống nghiệm | Đinh sắt (Iron), Copper(II)sulfate | Fe + CuSO₄ → FeSO₄ + Cu | Kim loại mạnh phản ứng với muối của kim loại yếu hơn tạo thành muối mới và kim loại mới | Dung dịch màu xanh nhạt dần, xuất hiện lớp đồng màu đỏ nâu bám trên đinh sắt |
9 | TINH BỘT VÀ CELLULOSE | Phản ứng màu của hồ tinh bột với iodine | Giá ống nghiệm, Ống nghiệm, Ống nhỏ giọt | Hồ tinh bột, Iodine |  | Trong tinh bột, các phân tử amylose có dạng xoắn, khi tương tác với iodine tạo ra màu xanh tím. Phản ứng này dùng để nhận biết tinh bột. | Dung dịch chuyển sang màu xanh tím. |
`;